/**
*
* @Author: Parsa Rajabi, ParsaRajabiPR [at] gmail.com
* @Date: August 2021
* @Description: Values Text
*
* */

export let VALUES = [
    "Achievement",
    "Balance",
    "Independence",
    "Influence",
    "Integrity",
    "Honesty",
    "Status",
    "Authority",
    "Responsibility",
    "Spirituality",
    "Fast paced",
    "Flexible",
    "Remote work",
    "Easy commute",
    "Learning",
    "Predictable",
    "Variety",
    "Quiet",
    "Relaxed",
    "Structured",
    "Unstructured",
    "Diversity",
    "Friendships",
    "Recognition",
    "Competition",
    "Teamwork",
    "Trust",
    "Creativity",
    "Security",
    "High earnings",
    "Decent earnings",
    "Leadership",
    "Managing",
]
export let VALUES_DEF = [
    "being able to meet my goals",
    "time for family, work, play",
    "doing projects by myself",
    "having an impact on others",
    "standing up for my beliefs",
    "telling the truth and knowing that others are telling the truth",
    "having an important job title or social standing",
    "making decisions that impact an organization",
    "trusted to deliver my work",
    "believing in my core beliefs",
    "work that has many things happening at once",
    "working on my own schedule",
    "doing work from anywhere in the world",
    "my workplace is close to where I live",
    "intellectually challenging work",
    "knowing what will happen day after day",
    "different types of work activities every day",
    "few disruptions throughout the day",
    "few pressures to get work done",
    "organized workplace",
    "planning how I do my work",
    "working with people of different backgrounds from me",
    "socializing with my co-workers",
    "being acknowledged for my work contributions",
    "healthy competition with my co-workers to inspire and to push me",
    "collaborating with my co-workers to get work done",
    "counting on my co-workers",
    "using my creative brain on the job",
    "knowing that my employer will keep me in my role for a long time",
    "making lots of money",
    "making enough money to live and to play",
    "influencing others",
    "overseeing the work of others",
]